# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Canadian Digital Service
email: cds-snc@tbs-sct.gc.ca
description: > # this means to ignore newlines until "baseurl:"
  The Canadian Digital Service (CDS) is bringing together the skills and expertise needed to accelerate this change.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://digital.canada.ca" # the base hostname & protocol for your site, e.g. http://example.com

include: ["_pages"]

# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

sass:
  style: compressed

# theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate-v2

exclude: ["Gemfile", "Gemfile.lock", "vendor", "docker-compose.yml", "README.md", "LICENSE.txt", "CONTRIBUTING.md", "_pages/en", "_posts/en", "index.html", "serve", "serve-fr", "check", "create-blog"]

defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        is_post: "true"

#paginate_path: "/pages/en/blog.html:5/"

pagination:
  enabled: true
  per_page: 5
  permalink: '/pages/:num/'
  sort_field: 'date'
  sort_reverse: true
  title: ':title'
  trail:
    before: 2
    after: 2